# Generated by Django 3.1.1 on 2020-09-19 22:31

import clientes.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', 'ClientsModel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created',
        ),
        migrations.RemoveField(
            model_name='client',
            name='modified',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=clientes.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
