# Generated by Django 3.1.1 on 2020-09-19 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
                ('refresh_token', models.CharField(max_length=256)),
            ],
        ),
    ]
