# Generated by Django 3.1.1 on 2020-09-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='client',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mercado_libre_user_id',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='client',
            name='token_type',
            field=models.CharField(default='', max_length=25),
        ),
    ]
